import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { AppSidebar } from "@/components/ui/app-sidebar";
import DarkVeil from "@/components/ui/darkVail";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Visora - Vibe is real",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Toaster />
          <div className="flex h-svh">
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset className="overflow-auto px-4 md:px-6 lg:px-8 scroll-smooth">
                <div className="flex max-lg:flex-col flex-1 gap-6 py-6 w-full max-w-7xl mx-auto justify-center h-full">

                  <div className="fixed top-0 left-0 h-dvh w-dvw -z-0 blur-2xl">
                    <DarkVeil />
                  </div>

                  <main className="z-10 w-full relative">
                    {children}
                  </main>
                </div>
              </SidebarInset>
            </SidebarProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
